cargo_toml_paths:
  - Cargo.toml
  - isopy/Cargo.toml
  - isopy-go/Cargo.toml
  - isopy-java/Cargo.toml
  - isopy-lib/Cargo.toml
  - isopy-python/Cargo.toml
  - isopy-repo/Cargo.toml
  - isopy-util/Cargo.toml
