#!/bin/bash
set -euo pipefail
this_dir=$(cd $(dirname $0); pwd -P)

cache_dir=$HOME/.isopy
python_version=3.11.1
tag=20230116

assets_dir=$cache_dir/assets
isopy_env_dir=$cache_dir/envs/isopy
isopy_env_path=$isopy_env_dir/env.json
python_dir_name=cpython-$python_version+$tag
isopy_python_dir=$isopy_env_dir/$python_dir_name
bin_dir=$HOME/.local/bin

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    python_file_name=$python_dir_name-x86_64-unknown-linux-gnu-install_only.tar.gz
elif [[ "$OSTYPE" == "darwin"* ]]; then
    python_file_name=$python_dir_name-x86_64-apple-darwin-install_only.tar.gz
else
    echo "Unsupported OS $OSTYPE"
fi

python_url=https://github.com/indygreg/python-build-standalone/releases/download/$tag/$python_file_name
python_path=$assets_dir/$python_file_name

mkdir -p $assets_dir
mkdir -p $isopy_python_dir

if [ ! -e $python_path ]; then
    mkdir -p $assets_dir
    curl -L $python_url --output $python_path
    set +e
    echo "$(cat $this_dir/sha256sums/$python_file_name.sha256)  $python_path" | \
        sha256sum --check --quiet -
    result=$?
    set -e
    if [ $result -ne 0 ]; then
        echo Checksum failed on $python_path
        rm -rf $python_path
        exit 1
    fi
fi

if [ ! -e $isopy_python_dir/bin ]; then
    T=$(mktemp -d -t isopy-bootstrap-XXXXXX)
    tar xf $python_path -C $T
    mkdir -p $isopy_python_dir
    mv $T/python/* $isopy_python_dir
    rm -rf $T
    PATH=$isopy_env_dir/$python_dir_name/bin:$PATH \
        python3 -m pip install --upgrade pip
    PATH=$isopy_env_dir/$python_dir_name/bin:$PATH \
        python3 -m pip install -r $this_dir/requirements.txt
fi

if [ -d $bin_dir ] && [ ! -e $bin_dir/isopy ]; then
    cat > $bin_dir/isopy <<EOF
#!/bin/bash
set -euo pipefail
isopy_dir=$(cd $(dirname $0); pwd -P)
PATH=$isopy_python_dir/bin:\$PATH \
  PYTHONPATH=\$isopy_dir \
  python3 \$isopy_dir/isopy_bin/main.py "\$@"
EOF
    chmod +x $bin_dir/isopy
    echo "Wrapper script created at $bin_dir/isopy; please make sure this path is on PATH"
else
    echo "Did not create bin wrapper script; create directory $bin_dir, add it to PATH and re-run bootstrap script"
fi

cat > $isopy_env_path <<EOF
name: isopy
python_dir: $python_dir_name
python_version: $python_version
tag: '$tag'
EOF
