[package]
name = "isopyrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.13", features = ["derive"] }
colour = "0.7.0"
exitcode = "1.1.2"
home = "0.5.4"
reqwest = { version = "0.11.15", features = ["blocking", "json", "serde_json"] }
rstest = "0.17.0"
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.94"
