[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true

[workspace]
members = [
  "isopy",
  "isopy-go",
  "isopy-java",
  "isopy-lib",
  "isopy-logging",
  "isopy-python",
  "isopy-repo",
  "isopy-util",
]
resolver = "2"
