[package]
authors = ["Richard Cook"]
description = "Isolated Python Tool"
edition = "2021"
homepage = "https://rcook.github.io/isopy/"
license = "MIT"
name = "isopy"
version = "0.0.24"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
async-trait = "0.1.68"
bytes = "1.4.0"
clap = { version = "4.1.13", features = ["derive"] }
colored = "2.0.0"
flate2 = "1.0.25"
futures-util = "0.3.28"
hex = "0.4.3"
home = "0.5.4"
include_dir = "0.7.3"
indicatif = "0.17.3"
lazy_static = "1.4.0"
md5 = "0.7.0"
path-absolutize = "3.0.14"
regex = "1.7.3"
remove_dir_all = "0.8.2" # https://github.com/rcook/isopy/security/dependabot/1
reqwest = { version = "0.11.16", features = ["stream"] }
rstest = "0.17.0"
same-file = "1.0.6"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
serde_yaml = "0.9.19"
sha2 = "0.10.6"
swiss-army-knife = { git = "https://github.com/rcook/swiss-army-knife-rs", tag = "v0.0.3" }
sysinfo = "0.28.4"
tar = "0.4.38"
tempdir = "0.3.7"
tinytemplate = "1.2.1"
tokio = { version = "1.27.0", features = ["full"] }

[target."cfg(any(target_os = \"linux\", target_os = \"macos\"))".dependencies]
exec = "0.3.1"

[target."cfg(target_os = \"linux\")".dependencies]
openssl-sys = { version = "0.9.84", features = ["vendored"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true
