#!/bin/bash
set -euo pipefail
this_dir=$(cd $(dirname $0); pwd -P)
cache_dir=$HOME/.isopy
assets_dir=$cache_dir/assets
isopy_env_dir=$cache_dir/env/isopy
python_dir_name=cpython-3.11.1+20230116
isopy_python_dir=$isopy_env_dir/$python_dir_name
python_url=https://github.com/indygreg/python-build-standalone/releases/download/20230116/$python_dir_name-x86_64-unknown-linux-gnu-install_only.tar.gz
python_file_name=$(basename $python_url)
python_path=$assets_dir/$python_file_name

mkdir -p $assets_dir
mkdir -p $isopy_python_dir

if [ ! -e $python_path ]; then
    mkdir -p $assets_dir
    curl -L -v $python_url --output $python_path
    set +e
    echo "$(cat $this_dir/sha256sums/$python_file_name.sha256)  $python_path" | \
        sha256sum --check --quiet -
    result=$?
    set -e
    if [ $result -ne 0 ]; then
        echo Checksum failed on $python_path
        rm -rf $python_path
        exit 1
    fi
fi

if [ ! -e $isopy_python_dir/bin ]; then
    T=$(mktemp -d -t isopy-bootstrap-XXXXXX)
    tar xf $python_path -C $T
    mkdir -p $isopy_python_dir
    mv $T/python/* $isopy_python_dir
    rm -rf $T
    PATH=$isopy_env_dir/$python_dir_name/bin:$PATH \
        python3 -m pip install --upgrade pip
    PATH=$isopy_env_dir/$python_dir_name/bin:$PATH \
        python3 -m pip install -r $this_dir/requirements.txt
fi
