[package]
authors = ["Richard Cook"]
categories = ["development-tools"]
description = "Isolated Python Tool - Java Support"
edition = "2021"
homepage = "https://rcook.github.io/isopy"
keywords = ["general"]
license = "MIT"
name = "isopy-java"
readme = "../README.md"
repository = "https://github.com/rcook/isopy.git"
version = "0.3.25"

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.81"
chrono = { version = "0.4.38", features = ["serde"] }
isopy-lib = { path = "../isopy-lib" }
joatmon = "0.0.34"
lazy_static = "1.5.0"
log = "0.4.22"
percent-encoding = "2.3.1"
reqwest = { version = "0.12.5", features = ["json"] }
serde = "1.0.206"
serde_json = "1.0.120"
serde_yaml = "0.9.34"
thiserror = "1.0.63"
url = { version = "2.5.2", features = ["serde"] }

[dev-dependencies]
rstest = "0.22.0"
