[package]
authors = ["Richard Cook"]
categories = ["development-tools"]
description = "Isolated Python Tool - Java Support"
edition = "2021"
homepage = "https://rcook.github.io/isopy"
keywords = ["general"]
license = "MIT"
name = "isopy-java"
readme = "../README.md"
repository = "https://github.com/rcook/isopy.git"
version = "0.4.4"

[dependencies]
anyhow = "1.0.93"
async-trait = "0.1.83"
isopy-lib = { path = "../isopy-lib" }
log = "0.4.22"
percent-encoding = "2.3.1"
reqwest = { version = "0.12.9", features = ["stream"] }
serde = "1.0.214"
serde_json = "1.0.133"
tokio = { version = "1.41.1", features = ["full"] }
url = { version = "2.5.3", features = ["serde"] }

[dev-dependencies]
rstest = "0.23.0"
