[package]
authors = ["Richard Cook"]
categories = ["development-tools"]
description = "Isolated Python Tool - Shared Library"
edition = "2021"
homepage = "https://rcook.github.io/isopy"
keywords = ["general"]
license = "MIT"
name = "isopy-lib"
readme = "../README.md"
repository = "https://github.com/rcook/isopy.git"
version = "0.3.16"

[dependencies]
anyhow = "1.0.80"
async-trait = "0.1.77"
bytes = "1.5.0"
futures-util = "0.3.30"
hex = "0.4.3"
joat-logger = "0.0.4"
joatmon = "0.0.33"
lazy_static = "1.4.0"
log = "0.4.21"
reqwest = { version = "0.11.25", features = ["stream"] }
rstest = "0.18.2"
serde = "1.0.197"
serde_json = "1.0.114"
sha2 = "0.10.8"
thiserror = "1.0.57"

[dev-dependencies]
rstest = "0.18.2"
