[package]
authors = ["Richard Cook"]
categories = ["development-tools"]
description = "Isolated Python Tool - Shared Library"
edition = "2021"
homepage = "https://rcook.github.io/isopy"
keywords = ["general"]
license = "MIT"
name = "isopy-lib"
repository = "https://rcook.github.io/isopy"
version = "0.1.4"

[dependencies]
anyhow = "1.0.71"
async-trait = "0.1.69"
bytes = "1.4.0"
futures-util = "0.3.28"
joat-logger = "0.0.1"
joatmon = "0.0.29"
log = "0.4.19"
reqwest = { version = "0.11.18", features = ["stream"] }
serde = "1.0.166"
serde_json = "1.0.99"
thiserror = "1.0.40"
