[package]
authors = ["Richard Cook"]
categories = ["development-tools"]
description = "Isolated Python Tool - Shared Library"
edition = "2024"
homepage = "https://rcook.github.io/isopy"
keywords = ["general"]
license = "MIT"
name = "isopy-lib"
readme = "../README.md"
repository = "https://github.com/rcook/isopy.git"
version = "0.5.11"

[dependencies]
anyhow = "1.0.99"
async-trait = "0.1.89"
chrono = "0.4.41"
decompress = { git = "https://github.com/rcook/decompress.git", rev = "c00c3b288e430eeffe78d3ba44952cf93697b1f0" }
derive_builder = "0.20.2"
derive_more = { version = "2.0.1", features = ["deref"] }
hex = "0.4.3"
indicatif = "0.17.11"
log = "0.4.27"
reqwest = { version = "0.12.23", features = ["stream"] }
sha2 = "0.10.9"
strum = "0.27.2"
strum_macros = "0.27.2"
tokio = { version = "1.47.1", features = ["full"] }
url = "2.5.7"

[dev-dependencies]
rstest = "0.25.0"

[lints.clippy]
all = { level = "deny", priority = -1 }
derive_partial_eq_without_eq = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
nursery = { level = "deny", priority = -1 }
option_if_let_else = "allow"
pedantic = { level = "deny", priority = -1 }
