[package]
authors = ["Richard Cook"]
categories = ["development-tools"]
description = "Isolated Python Tool - Shared Library"
edition = "2021"
homepage = "https://rcook.github.io/isopy"
keywords = ["general"]
license = "MIT"
name = "isopy-lib"
readme = "../README.md"
repository = "https://github.com/rcook/isopy.git"
version = "0.3.10"

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.73"
bytes = "1.5.0"
futures-util = "0.3.28"
hex = "0.4.3"
joat-logger = "0.0.4"
joatmon = "0.0.33"
log = "0.4.20"
reqwest = { version = "0.11.20", features = ["stream"] }
rstest = "0.18.2"
serde = "1.0.188"
serde_json = "1.0.107"
sha2 = "0.10.7"
thiserror = "1.0.48"

[dev-dependencies]
rstest = "0.18.2"
