[package]
authors = ["Richard Cook"]
categories = ["development-tools"]
description = "Isolated Python Tool - Shared Library"
edition = "2021"
homepage = "https://rcook.github.io/isopy"
keywords = ["general"]
license = "MIT"
name = "isopy-lib"
repository = "https://rcook.github.io/isopy"
version = "0.3.1"

[dependencies]
anyhow = "1.0.72"
async-trait = "0.1.71"
bytes = "1.4.0"
futures-util = "0.3.28"
hex = "0.4.3"
joat-logger = "0.0.1"
joatmon = "0.0.30"
log = "0.4.19"
reqwest = { version = "0.11.18", features = ["stream"] }
rstest = "0.18.1"
serde = "1.0.171"
serde_json = "1.0.103"
sha2 = "0.10.7"
thiserror = "1.0.43"

[dev-dependencies]
rstest = "0.18.1"
