[package]
authors = ["Richard Cook"]
categories = ["development-tools"]
description = "Isolated Python Tool"
edition = "2021"
homepage = "https://rcook.github.io/isopy"
keywords = ["general"]
license = "MIT"
name = "isopy-lib"
readme = "README.md"
repository = "https://github.com/rcook/isopy-tng.git"
version = "0.0.0"

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.81"
rstest = "0.22.0"
sanitise-file-name = "1.0.0"
serde_json = "1.0.127"

[dev-dependencies]
rstest = "0.22.0"
