[package]
authors = ["Richard Cook"]
categories = ["development-tools"]
description = "Isolated Python Tool - Shared Library"
edition = "2021"
homepage = "https://rcook.github.io/isopy"
keywords = ["general"]
license = "MIT"
name = "isopy-lib"
readme = "../README.md"
repository = "https://github.com/rcook/isopy.git"
version = "0.3.25"

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.80"
bytes = "1.6.0"
futures-util = "0.3.30"
hex = "0.4.3"
joat-logger = "0.0.5"
joatmon = "0.0.34"
lazy_static = "1.4.0"
log = "0.4.21"
reqwest = { version = "0.12.4", features = ["stream"] }
rstest = "0.19.0"
serde = "1.0.202"
serde_json = "1.0.117"
sha2 = "0.10.8"
thiserror = "1.0.61"

[dev-dependencies]
rstest = "0.19.0"
