[package]
authors = ["Richard Cook"]
categories = ["development-tools"]
description = "Isolated Python Tool - Shared Library"
edition = "2021"
homepage = "https://rcook.github.io/isopy"
keywords = ["general"]
license = "MIT"
name = "isopy-lib"
readme = "../README.md"
repository = "https://github.com/rcook/isopy.git"
version = "0.3.25"

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.82"
derive_more = { version = "1.0.0", features = ["deref"] }
hex = "0.4.3"
lazy_static = "1.5.0"
reqwest = { version = "0.12.7", features = ["stream"] }
serde = "1.0.209"
sha2 = "0.10.8"
thiserror = "1.0.63"
tokio = { version = "1.40.0", features = ["full"] }
url = "2.5.2"

[dev-dependencies]
rstest = "0.22.0"
