[package]
authors = ["Richard Cook"]
categories = ["development-tools"]
description = "Isolated Python Tool - OpenJDK Support"
edition = "2021"
homepage = "https://rcook.github.io/isopy"
keywords = ["general"]
license = "MIT"
name = "isopy-openjdk"
repository = "https://rcook.github.io/isopy"
version = "0.1.4"

[dependencies]
anyhow = "1.0.71"
isopy-lib = { path = "../isopy-lib" }
percent-encoding = "2.3.0"
serde = "1.0.164"
thiserror = "1.0.40"
