#!/bin/bash
set -euo pipefail

usage() {
    echo 'Usage: setup [-h] [--force] [--stdout] [SCRIPT_PATH]'
    echo ''
    echo '  SCRIPT_PATH  path to wrapper script'
    echo '  --force      force overwrite of wrapper script if it already exists'
    echo '  --stdout     write wrapper script to stdout'
    echo ''
    echo 'Visit https://github.com/rcook/isopy for more information'
}

if [ $# -eq 0 ]; then
    usage
    exit 1
fi

if ([ $# -eq 1 ] && ( [ "$1" == '-h' ] || [ "$1" == '--help' ] )); then
    usage
    exit 0
fi

script_path=
force=
stdout=
while [ $# -gt 0 ]; do
    arg=$1
    shift

    if [ "$arg" == '-f' ] || [ "$arg" == '--force' ]; then
        if [ "$force" != '' ]; then
            echo '--force already specified'
            echo ''
            usage
            exit 1
        fi
        force=1
        continue
    fi

    if [ "$arg" == '-o' ] || [ "$arg" == '--stdout' ]; then
        if [ "$stdout" != '' ]; then
            echo '--stdout already specified'
            echo ''
            usage
            exit 1
        fi
        stdout=1
        continue
    fi

    if [[ "$arg" = -* ]]; then
        echo "Invalid option $arg"
        echo ''
        usage
        exit 1
    fi

    if [ "$script_path" != '' ]; then
        echo 'Script path already specifed'
        echo ''
        usage
        exit 1
    fi
    script_path=$(realpath $arg)
done

if [ "$force" == '' ] && [ -e "$script_path" ]; then
    echo "Script $script_path already exists; specify --force to overwrite it"
    exit 1
fi

isopy_branch=main
isopy_url=https://github.com/rcook/isopy/archive/refs/heads/$isopy_branch.zip
isopy_dir=$HOME/.isopy
isopy_src_dir=$isopy_dir/src
isopy_assets_dir=$isopy_dir/assets
isopy_branch_dir=$isopy_src_dir/$isopy_branch
isopy_env_dir=$isopy_dir/envs/isopy
isopy_env_path=$isopy_env_dir/env.yaml
isopy_env_python_dir=$isopy_env_dir/python

temp_dir=$(mktemp -d -t isopy-setup-XXXXXX)
trap 'rm -rf -- "$temp_dir"' EXIT

if [ ! -e $isopy_branch_dir ]; then
    temp_zip_dir=$temp_dir/isopy-$isopy_branch
    temp_zip_path=$temp_zip_dir.zip
    curl -L $isopy_url --output $temp_zip_path
    unzip -q $temp_zip_path -d $temp_dir
    mkdir -p $isopy_branch_dir
    temp=$temp_dir/$isopy_branch
    mv $temp_zip_dir $temp
    mv $temp $isopy_src_dir
fi

python_version=$(cat $isopy_branch_dir/.isopy.yaml | sed -En "s/^python_version: ['\"]?([^'\"]+)['\"]?$/\1/p")
tag=$(cat $isopy_branch_dir/.isopy.yaml | sed -En "s/^tag: ['\"]?([^'\"]+)['\"]?$/\1/p")
python_base_name=cpython-$python_version+$tag
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    python_file_name=$python_base_name-x86_64-unknown-linux-gnu-install_only.tar.gz
elif [[ "$OSTYPE" == "darwin"* ]]; then
    python_file_name=$python_base_name-x86_64-apple-darwin-install_only.tar.gz
else
    echo "Unsupported OS $OSTYPE"
fi

python_url=https://github.com/indygreg/python-build-standalone/releases/download/$tag/$python_file_name
python_path=$isopy_assets_dir/$python_file_name

mkdir -p $isopy_assets_dir
mkdir -p $isopy_env_python_dir

if [ ! -e $python_path ]; then
    curl -L $python_url --output $python_path
    set +e
    echo "$(cat $isopy_branch_dir/sha256sums/$python_file_name.sha256)  $python_path" | \
        sha256sum --check --quiet -
    result=$?
    set -e
    if [ $result -ne 0 ]; then
        echo Checksum failed on $python_path
        rm -rf $python_path
        exit 1
    fi
fi

if [ ! -e $isopy_env_python_dir/bin ]; then
    tar xf $python_path -C $temp_dir
    mkdir -p $isopy_env_python_dir
    mv $temp_dir/python/* $isopy_env_python_dir
    PATH=$isopy_env_python_dir/bin:$PATH \
        python3 -m pip install --upgrade pip
    PATH=$isopy_env_python_dir/bin:$PATH \
        python3 -m pip install -r $isopy_branch_dir/requirements.txt
fi

cat > $isopy_env_path <<EOF
name: isopy
python_dir: python
python_version: $python_version
tag: '$tag'
EOF

if [ "$stdout" == '1' ]; then
    output=/dev/stdout
    echo ''
    echo ''
    echo '--------------------------------------------------'
    echo 'Copy and paste this into an executable shell script on PATH'
    echo '--------------------------------------------------'
elif [ "$script_path" != '' ]; then
    output=$script_path
fi

if [ "$output" != '' ]; then
    cat > $output <<EOF
#!/bin/bash
set -euo pipefail
PATH=$isopy_env_python_dir/bin:\$PATH \\
  PYTHONPATH=$isopy_branch_dir \\
  exec python3 $isopy_branch_dir/isopy_bin/main.py "\$@"
EOF
    if [ "$script_path" != '' ]; then
        chmod +x $output
        echo "Wrapper script generated at $output; please make sure this file is on PATH"
    fi
fi

if [ "$stdout" == '1' ]; then
    echo '--------------------------------------------------'
    echo ''
    echo '--------------------------------------------------'
    echo 'Or stick this at the top of one of your shell config files:'
    echo '--------------------------------------------------'
    echo "export PATH=$isopy_env_python_dir/bin:\$PATH"
    echo '--------------------------------------------------'
    echo ''
    echo 'For further instructions, go to https://github.com/rcook/isopy'
fi
