name: CI

env:
  CARGO_TERM_COLOR: always
  project: isopy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 0 * * SUN

jobs:
  ci:
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
        include:
          - target: x86_64-apple-darwin
            host_os: macos-latest
          - target: x86_64-pc-windows-msvc
            host_os: windows-latest
          - target: x86_64-unknown-linux-gnu
            host_os: ubuntu-latest
    runs-on: ${{ matrix.host_os }}
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Build (debug)
        run: cargo build --verbose --target ${{ matrix.target }}
      - name: Run tests (debug)
        run: cargo test --verbose --target ${{ matrix.target }}
      - name: Build (release)
        run: cargo build --verbose --release --target ${{ matrix.target }}
      - name: Run tests (release)
        run: cargo test --verbose --release --target ${{ matrix.target }}
