name: CI

env:
  CARGO_TERM_COLOR: always
  project: isopy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 0 * * SUN

jobs:
  ci:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Build (debug)
        run: cargo build --verbose
      - name: Run tests (debug)
        run: cargo test --verbose
      - name: Build (release)
        run: cargo build --verbose --release
      - name: Run tests (release)
        run: cargo test --verbose --release
